---
apiVersion: v1
kind: Service
metadata:
  namespace: argocd
  name: argocd-server-internal-lb-l4
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: argocd-server-internal-lb-l4
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080