# Sample manifest for deploying external LB on public IP (takes few minutes to succeed!).
# Public IP can be identified by "kubectl get ingress lb-external".
# LB, ForwardingRule, NEG are created automatically.

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hostname-external
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: lala.sandbox.pan-net.cloud
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: hostname-external
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hostname-external
spec:
  type: NodePort
  selector:
    app: hostname-external
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9376

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-external
  labels:
    app: hostname-external
spec:
  selector:
    matchLabels:
      app: hostname-external
  replicas: 3
  template:
    metadata:
      labels:
        app: hostname-external
    spec:
      containers:
      - image: k8s.gcr.io/serve_hostname:v1.4
        name: hostname-external
        ports:
        - containerPort: 9376
          protocol: TCP