---
- name: Deploy kube-prometheus-stack Helm chart
  hosts: jh
  become: yes
  gather_facts: no
  tasks:
    - name: Deploy kube-prometheus-stack
      become_user: user
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          --version {{ kube_prometheus_stack }} \
          --create-namespace \
          --wait-for-jobs \
          --timeout 5m \
          --namespace promstack
