trigger:
  #batch: true
  branches:
    include:
      - 'prod'
    exclude:
      - 'main'
      - 'docs'
  paths:
    include:
      - '.azure-devops/**'
      - 'infrastructure/**'
      - 'configuration/**'

#trigger: none

pr:
  branches:
    include:
      - 'prod'
    exclude:
      - 'main'
      - 'docs'
  paths:
      include:
        - '.azure-devops/**'
        - 'infrastructure/**'
        - 'configuration/**'

pool:
  vmImage: ubuntu-latest

container: ubuntu:18.04

variables:
- name: TF_LOG
  value: DEBUG
- name: CONF_DIR
  value: configuration
- name: INFRA_DIR
  value: infrastructure
- name: INFRA_ENV
  value: $(Build.SourceBranchName)
## - name: GOOGLE_CREDENTIALS
##   value: "${{ secrets.GCP_SA }}"

# Params for manually triggered pipelines
parameters:
- name: environment
  displayName: 'Environment'
  type: string
  default: 'prod'

steps:
- script: echo Hello ${{ parameters.environment }}.
  displayName: 'Run a one-line script'
- script: echo Hello ${{ variables.INFRA_ENV }}.
  displayName: 'Run a one-line script'

