trigger:
  batch: true
  branches:
    include:
      - 'main'
    exclude:
      - 'docs'
  paths:
    include:
      - '.azure-devops/**'

pr:
  branches:
    include:
      - 'main'
    exclude:
      - 'docs'

pool:
  vmImage: ubuntu-latest

container: ubuntu:18.04

parameters:
- name: name
  displayName: 'Username'
  type: string
  default: 'juraj'

steps:
- script: echo Hello ${{ parameters.name }}.
  displayName: 'Run a one-line script'


