---
apiVersion: v1
kind: Service
metadata:
  name: argo-server-internal-lb-l4
  namespace: argo
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: argo-server-internal-lb-l4
spec:
  type: LoadBalancer
  selector:
    app: argo-server
  ports:
  - name: http
    port: 2746
    protocol: TCP
    targetPort: 2746
