---
- import_playbook: includes/jumphost/bootstrap-jh.yaml
- import_playbook: includes/k8s/bootstrap-k8s.yaml
- import_playbook: includes/argo/argocd.yaml
- import_playbook: includes/argo/argo.yaml
- import_playbook: includes/logging-monitoring/gcp-ops-agent.yaml
- import_playbook: includes/logging-monitoring/kube-prometheus-stack.yaml
