---
- import_playbook: includes/jumphost/bootstrap-jh.yaml
- import_playbook: includes/k8s/bootstrap-k8s.yaml
- import_playbook: includes/argo/argo-cd.yaml
- import_playbook: includes/argo/argo-events.yaml
- import_playbook: includes/argo/argo-workflows.yaml
- import_playbook: includes/logging-monitoring/gcp-ops-agent.yaml
- import_playbook: includes/logging-monitoring/kube-prometheus-stack.yaml
