name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: debian:stable-slim
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scripts
        run: |
          echo ${GITHUB_WORKSPACE}
          cat ${GITHUB_WORKSPACE}/project.vars
          source ${GITHUB_WORKSPACE}/project.vars
  
  GCP:
    runs-on: ubuntu-latest
    container: debian:stable-slim
    steps:
      - name: GCP call
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: dso-master
          APPLICATION_CREDENTIALS: ${{secrets.SA_OWNER_DSO_MASTER}}
        with:
          args: compute instances list


