name: deploy-gke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-gke:
    runs-on: ubuntu-latest
    container: jkosik/cloud-deployer
    defaults:
      run:
        shell: bash
#        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up GCP Cloud SDK for Master
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: dso-master
          service_account_key: ${{ secrets.SA_OWNER_DSO_MASTER }}

      # - name: Deploy Client GKE    
      #   run: |
      #     echo "Deploying to $DSO_PROJECT"
      #     source deployment.sh

      - name: Load environment variables to GITHUB_ENV map
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < gcp-client/project.vars

      - name: Read variables
        run: echo ${{ env }}

      - name: Set up GCP Cloud SDK for Client
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.DSO_PROJECT }}
          service_account_key: ${{ secrets.SA_OWNER_DSO_GKE_CLIENT_1 }}

      - name: Grab data from GCP
        run: |
          gcloud config set compute/region ${{ env.DSO_GCP_REGION }}
          gcloud config set compute/zone ${{ env.DSO_GCP_ZONE }}
          echo "Client GKE in state:" $(gcloud container clusters describe ${{ env.DSO_PROJECT }} --format="value(status)")
          JH_IP=$(gcloud compute instances describe jh --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
          echo "Jumphost listening on:" $JH_IP
          echo "JH_IP=$JH_IP" >> $GITHUB_ENV

      - name: Test Jumphost
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "Deploying to ${{ env.DSO_PROJECT }}"
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
         
          ssh-keyscan -H ${{ env.JH_IP }} >> ~/.ssh/known_hosts          
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GCP_SSH_PRIVATE_KEY }}"
         
          echo "Running commands from inside jumphost at:" ${{ env.JH_IP }}
          #ssh -o StrictHostKeyChecking=no user@$JH_IP "gcloud projects list"
          #ssh -o StrictHostKeyChecking=no user@$JH_IP "kubectl get ns"
          ssh user@${{ env.JH_IP }} "gcloud projects list"
          ssh user@${{ env.JH_IP }} "kubectl get ns"          
 