name: deploy-gke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-gke:
    runs-on: ubuntu-latest
    container: jkosik/cloud-deployer
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: dso-master
          service_account_key: ${{ secrets.SA_OWNER_DSO_MASTER }}
          export_default_credentials: true

      - name: Source project.vars
        run: |
          source gcp-client/project.vars
          echo "Deploying to $DSO_PROJECT"

      # - name: Deploy GKE    
      #   run: |
      #     source deployment.sh

      - name: SSH auth
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts          
          ssh-keyscan -H 34.116.209.201 >> ~/.ssh/known_hosts          
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GCP_SSH_PRIVATE_KEY }}"
          mkdir ~/.ssh
          

      - name: Jumphost tests
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock          
        run: |

          #gcloud container clusters describe $DSO_PROJECT --format="value(status)"
          #gcloud compute instances describe jh --format='get(networkInterfaces[0].accessConfigs[0].natIP)'
          #JH_IP=$(gcloud compute instances describe jh --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
          JH_IP=34.116.209.201
          #ssh -o StrictHostKeyChecking=no user@$JH_IP "gcloud projects list"
          #ssh -o StrictHostKeyChecking=no user@$JH_IP "kubectl get ns"
          ssh user@$JH_IP "gcloud projects list"
          ssh user@$JH_IP "kubectl get ns"

 