name: deploy-gke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-gke:
    runs-on: ubuntu-latest
    container: jkosik/cloud-deployer
    defaults:
      run:
        shell: bash
#        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up GCP Cloud SDK for Master
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: dso-master
          service_account_key: ${{ secrets.SA_OWNER_DSO_MASTER }}

      # - name: Deploy Client GKE    
      #   run: |
      #     echo "Deploying to $DSO_PROJECT"
      #     source deployment.sh

      - name: Source Client variables
        run: |
          source gcp-client/project.vars

      - name: dotenv
        id: dotenv
        uses: gcp-client/project.vars

      - name: lala
        run: cat ${{ steps.dotenv.outputs.DSO_PROJECT }}

      - name: Set up GCP Cloud SDK for Client
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: $DSO_PROJECT
          service_account_key: ${{ secrets.SA_OWNER_DSO_GKE_CLIENT_1 }}

      - name: Grab data from GCP
        run: |
          source gcp-client/project.vars
          gcloud config set compute/region $DSO_GCP_REGION
          gcloud config set compute/zone $DSO_GCP_ZONE
          gcloud container clusters describe $DSO_PROJECT --format="value(status)"
          gcloud compute instances describe jh --format='get(networkInterfaces[0].accessConfigs[0].natIP)'
          JH_IP=$(gcloud compute instances describe jh --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
          echo $JH_IP

      - name: Test Jumphost
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "Deploying to $DSO_PROJECT"
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts          
          ssh-keyscan -H 34.116.209.201 >> ~/.ssh/known_hosts          
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GCP_SSH_PRIVATE_KEY }}"

          JH_IP=34.116.209.201
          #ssh -o StrictHostKeyChecking=no user@$JH_IP "gcloud projects list"
          #ssh -o StrictHostKeyChecking=no user@$JH_IP "kubectl get ns"
          ssh user@$JH_IP "gcloud projects list"
          ssh user@$JH_IP "kubectl get ns"          

      - name: Jumphost tests
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock          
        run: |
          JH_IP=34.116.209.201
          #ssh -o StrictHostKeyChecking=no user@$JH_IP "gcloud projects list"
          #ssh -o StrictHostKeyChecking=no user@$JH_IP "kubectl get ns"
          ssh user@$JH_IP "gcloud projects list"
          ssh user@$JH_IP "kubectl get ns"

 